FROM docker.io/library/php:8.2-fpm

RUN apt-get update
RUN apt-get install -y git libzip-dev zip unzip npm

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# install db drivers
RUN apt-get install -y libpq5 libpq-dev;
RUN docker-php-ext-install pdo pdo_pgsql;
RUN apt-get autoremove --purge -y libpq-dev;
RUN apt-get clean;
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -d /home/user user
RUN mkdir -p /home/user/.composer && \
    chown -R user:user /home/user

RUN mkdir -p /app && \
    chown -R user:user /app

# Set working directory
WORKDIR /app

USER user
